In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [5]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(5,)
5
1
float64


In [12]:
arr2 = np.array([[1,2],[3,4]])
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)
print(arr2.dtype)

(2, 2)
4
2
int32


In [13]:
a1 = np.array([1,2,3,4,5])
sum = np.sum(a1)
max = np.max(a1)
min = np.min(a1)
mean = np.mean(a1)
std = np.std(a1)
print("sum = ",sum)
print("max = ",max)
print("min = ",min)
print("mean = ",mean)
print("std = ",std)

sum =  15
max =  5
min =  1
mean =  3.0
std =  1.4142135623730951


In [14]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

sum = m1 + m2
diff = m1 - m2
prod = m1 * m2
dotProd = np.dot(m1,m2)
print("sum = ",sum)
print("diff = ",diff)
print("prod = ",prod)
print("dotProd = ",dotProd)

sum =  [[ 6  8]
 [10 12]]
diff =  [[-4 -4]
 [-4 -4]]
prod =  [[ 5 12]
 [21 32]]
dotProd =  [[19 22]
 [43 50]]


In [15]:
from numpy import random as r

In [16]:
a1 = r.rand(5)
print(a1)

[0.29507304 0.32548574 0.94022028 0.57409951 0.96680198]


In [22]:
a1 = r.randint(1,100,10)
print(a1)

[73 37 10 50  1 40 41 77 15 32]
<class 'numpy.ndarray'>


In [24]:
a = [3,6,7,9,12]
random = r.choice(a)
print("random from choice = ",random)

random from choice =  3


In [45]:
lst = np.array([10,20,30,40,50])
r.shuffle(lst)
print(lst)

[20 30 50 40 10]


In [29]:
set1 = np.array([1,1,1,2,3,4,5])
set2 = np.array([4,5,6,7])
print("unique set1 = ",np.unique(set1))
print("union = ",np.union1d(set1,set2))
print("intersection = ",np.intersect1d(set1,set2))
print("symmetric = ",np.setxor1d(set1,set2))

unique set1 =  [1 2 3 4 5]
union =  [1 2 3 4 5 6 7]
intersection =  [4 5]
symmetric =  [1 2 3 6 7]


In [38]:
def add(x,y):
    return x+y
sumlst = list(map(add,[1,2,3,4,5],[4,5,6,7,8]))
print(sumlst)

[5, 7, 9, 11, 13]


In [36]:
def add(x,y):
    return x+y
myadd = np.frompyfunc(add,2,1)
print(myadd([1,2,3,4,5],[4,5,6,7,8]))

[5 7 9 11 13]


In [51]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
c1 = a1.copy()
c2 = a1[1:10:2].copy()
indices = [0,2,4]
print(a1[indices])
print(a1)
print(c1)
print(c2)

[1 3 5]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [61]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original data : \n",data)
print("saving data in data.txt...")
np.savetxt('data.txt',data,delimiter=",", fmt='%d')
loaded_data = np.loadtxt('data.txt', delimiter=",")
print("Loaded data from data.txt:\n", loaded_data)

Original data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
saving data in data.txt...
Loaded data from data.txt:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [62]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original data : \n",data)
print("saving data in data.txt...")
np.savetxt('data.csv',data,delimiter=",", fmt='%d')
loaded_data = np.loadtxt('data.csv', delimiter=",")
print("Loaded data from data.txt:\n", loaded_data)

Original data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
saving data in data.txt...
Loaded data from data.txt:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [64]:
data = np.array([1,2,3,np.nan,5])
clean_data = data[~np.isnan(data)]
print(data)
print(clean_data)
mean_value = np.nanmean(data)
print("Mean ignoring NaN:", mean_value)

[ 1.  2.  3. nan  5.]
[1. 2. 3. 5.]
Mean ignoring NaN: 2.75


In [65]:
import pandas as pd

In [69]:
list1 = [10,20,30,40,50]
array1 = pd.array(list1)
series_list = pd.Series(list1)
series_array = pd.Series(array1)
print("list = ",list1,"\n")
print("pd array = ",array1,"\n")
print("series_list: \n",series_list,"\n")
print("series_array: \n",series_array)

list =  [10, 20, 30, 40, 50] 

pd array =  <IntegerArray>
[10, 20, 30, 40, 50]
Length: 5, dtype: Int64 

series_list: 
 0    10
1    20
2    30
3    40
4    50
dtype: int64 

series_array: 
 0    10
1    20
2    30
3    40
4    50
dtype: Int64


In [77]:
list1_labelled = pd.Series(list1, index=["A","B","C","D","E"])
print(list1_labelled)
print("\n",type(list1_labelled))
print("\n",list1_labelled.shape)
print("\n",list1_labelled.values)
print("\n",list1_labelled.index)

A    10
B    20
C    30
D    40
E    50
dtype: int64

 <class 'pandas.core.series.Series'>

 (5,)

 [10 20 30 40 50]

 Index(['A', 'B', 'C', 'D', 'E'], dtype='object')


In [81]:
label_list = ['Tata','Birla','Wipro','Infosys','HCL']
ps1 = pd.Series(list1, index=label_list)
print(ps1)
print("\n",ps1["Tata"])
print("\n",ps1["Tata":"Infosys"])
print("\n",ps1["Tata":"Infosys":2])

Tata       10
Birla      20
Wipro      30
Infosys    40
HCL        50
dtype: int64

 10

 Tata       10
Birla      20
Wipro      30
Infosys    40
dtype: int64

 Tata     10
Wipro    30
dtype: int64


In [85]:
mask1 = ps1>10
mask2 = ps1+1
print(mask1)
print("\n",mask2)

Tata       False
Birla       True
Wipro       True
Infosys     True
HCL         True
dtype: bool

 Tata       11
Birla      21
Wipro      31
Infosys    41
HCL        51
dtype: int64


In [87]:
student = ["Ramesh","Suresh","Mukesh","Rajesh","Subhash"]
df1 = pd.DataFrame(student, columns=['Students'])
df1

Students
0   Ramesh
1   Suresh
2   Mukesh
3   Rajesh
4  Subhash

In [90]:
grades = ["A","A+","B","B+","C"]
df2 = pd.DataFrame({"Students":student, "Grades":grades})
df2

Students Grades
0   Ramesh      A
1   Suresh     A+
2   Mukesh      B
3   Rajesh     B+
4  Subhash      C

In [94]:
df2["Students"]

0     Ramesh
1     Suresh
2     Mukesh
3     Rajesh
4    Subhash
Name: Students, dtype: object

In [93]:
df2[::12]

Students Grades
0   Ramesh      A

In [95]:
df2.loc[1]

Students    Suresh
Grades          A+
Name: 1, dtype: object

In [96]:
df2.loc[1, "Grades"]

'A+'

In [97]:
df2.loc[4, "Students"]

'Subhash'

In [98]:
df2["Location"] = ["Bangalore","Chennai","Mumbai","Kolkata","Delhi"]
df2

Students Grades   Location
0   Ramesh      A  Bangalore
1   Suresh     A+    Chennai
2   Mukesh      B     Mumbai
3   Rajesh     B+    Kolkata
4  Subhash      C      Delhi

In [99]:
df2.drop("Location",axis=1,inplace=True)
df2

Students Grades
0   Ramesh      A
1   Suresh     A+
2   Mukesh      B
3   Rajesh     B+
4  Subhash      C

In [101]:
data_cust = pd.DataFrame({'customerID':["101","102","103","104"],
                          "category":['Medium','Medium','High','Low'],
                          'first_visit': ['yes','yes','no','yes'],
                          'sales':[123,9,32,214]})
data_cust

customerID category first_visit  sales
0        101   Medium         yes    123
1        102   Medium         yes      9
2        103     High          no     32
3        104      Low         yes    214

In [ ]:
data_cust_new = pd.DataFrame({'customerID':["101","102","103","104"],
                          "category":['Medium','Medium','High','Low'],
                          'first_visit': ['yes','yes','no','yes'],
                          'sales':[123,9,32,214]})
data_cust_new

In [ ]:
merged_data_cust = pd.


In [106]:
df1 = pd.read_csv('sales_data_sample.csv', encoding='ISO-8859-1')
df1.head()

ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00   
1        10121               34      81.35                5  2765.90   
2        10134               41      94.74                2  3884.34   
3        10145               45      83.26                6  3746.70   
4        10159               49     100.00               14  5205.27   

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...   
1    5/7/2003 0:00  Shipped       2         5     2003  ...   
2    7/1/2003 0:00  Shipped       3         7     2003  ...   
3   8/25/2003 0:00  Shipped       3         8     2003  ...   
4  10/10/2003 0:00  Shipped       4        10     2003  ...   

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY   
1             59 rue de l'Abbaye           NaN          Reims   NaN   
2  27 rue du Colonel Pierre Avia           NaN          Paris   NaN   
3             78934 Hillside Dr.           NaN       Pasadena    CA   
4                7734 Strong St.           NaN  San Francisco    CA   

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE  
0      10022     USA       NaN              Yu             Kwai    Small  
1      51100  France      EMEA         Henriot             Paul    Small  
2      75508  France      EMEA        Da Cunha           Daniel   Medium  
3      90003     USA       NaN           Young            Julie   Medium  
4        NaN     USA       NaN           Brown            Julie   Medium  

[5 rows x 25 columns]